### ISSUE TITLE
this is great. it needs a declarative API as well, managed by `componentWillReceiveProps`

### ISSUE THREAD

**Issue by faceyspacey** [iktw/react-native-hud-view#1]
Here's the common example for how things like Modals, StatusBars, etc, are made to have a declarative interface:

```
componentWillReceiveProps(nextProps) {
    if(nextProps.isVisible && !props.isVisible) this.show();
    else if(!nextProps.isVisible && props.isVisible) this.hide();
}
```

In my opinion, the perfect such component should have both a declarative and imperative interface. There's just times where you need an imperative interface. But overall, we should be guiding people to declarative coding as much as possible.

**Comment by mohammedhammoud** [comment]
#7 You are correct. I've added this possibility.
