### ISSUE TITLE
error: Invalid filename.  Unable to add.

### ISSUE THREAD

**Issue by engmsaleh** [iktw/react-native-hud-view#10]
I got the following error when I try to make an Android release

`:app:processReleaseResources/Users/mohamedsaleh/Repos/stock-troll/android/app/build/intermediates/res/merged/release/drawable-mdpi/node_modules_reactnativehudview_node_modules_reactnative_libraries_customcomponents_navigationexperimental_assets_backicon.png: error: Invalid filename.  Unable to add.`

**Comment by engmsaleh** [comment]
The only way I have solved this, is to go the `Package.json` file inside `react-native-hud-view` and delete `react` and `react-native` from their as dependancies

**Comment by mohammedhammoud** [comment]
Fixed in latest version
