### ISSUE TITLE
It would be better if can show error message

### ISSUE THREAD

**Issue by sunkehappy** [iktw/react-native-hud-view#4]
Sometimes we want to tell user what kind of error happened. Is this an acceptable idea?

**Comment by mohammedhammoud** [comment]
@sunkehappy You could pass a custom component to the showCustomComponent() method:
```
var customComponent = (<Text style={{color: "#ffffff"}}>Some error message</Text>)
this.refs.hudView.showCustomComponent(customComponent)
```
https://github.com/iktw/react-native-hud-view#show-custom-component-hud

**Comment by waltermvp** [comment]
@sunkehappy do you have examples on how to add a custom component delcaratively?
